#!/bin/bash

declare -A sites=(
  ["Whatsapp"]="https://web.whatsapp.com/"
  ["Facebook"]="https://www.facebook.com"
  ["Instagram"]="https://www.instagram.com/"
  ["YouTube"]="https://www.youtube.com"
  ["Bilibili china"]="https://www.bilibili.com/"
  ["Bilibili world"]="https://www.bilibili.tv/en"
  ["Discoard"]="https://discord.com/channels/@me"
  ["Twitch"]="https://www.twitch.tv/"
  ["Kick"]="https://kick.com/"
  ["TikTok"]="https://www.tiktok.com/es-419/"
  ["Gato"]="https://www.tiktok.com/@ghoshtv?_r=1&_t=ZS-99Pgkvj68rB"
  ["GitHub"]="https://github.com/juanest2025"
  ["La.movie"]="https://lamovie.org/"
  ["hell mode"]="https://animeav1.com/media/hell-mode-yarikomizuki-no-gamer-wa-hai-settei-no-isekai-de-musou-suru-2nd-season/7"
  ["Tioplus.app"]="https://tioplus.app/"
  ["Cuevana 1"]="https://cuevana8.net/"
  ["Cuevana 2"]="https://lacuevana.org/"
  ["Cuevana 3"]="https://cuevanapro.org/"
  ["Goojara"]="https://ww1.goojara.to/ejdWP7"
  ["Flathub"]="https://flathub.org/es"
  ["kimcartoon"]="https://kimcartoon.com.co/"
  ["Spider man brand new day"]="https://cuevana3l.biz/pelicula/spider-man-un-nuevo-dia"
  ["Miraculos.to"]="https://miraculous.to/en/"
  ["Ladyblognews"]="https://ladyblognews.com/"
  ["Claude AI"]="https://claude.ai/new"
  ["ChatGPT"]="https://chatgpt.com/"
  ["DeepSeek"]="https://chat.deepseek.com/"
  ["Kimi K3"]="https://www.kimi.com/"
  ["Gemini"]="https://gemini.google.com/app"
  ["Sesame"]="https://app.sesame.com"
  ["Tioanime"]="https://tioanime.com/"
  ["Tiohentai"]="https://tiohentai.com/"
  ["anime-jl"]="https://www.anime-jl.net/"
  ["AnimeAV1"]="https://animeav1.com/"
  ["Animejara"]="https://animejara.com/"
  ["latanime"]="https://latanime.org/"
  ["Hentaila"]="https://hentaila.com/hub"
  ["hentai-jl"]="https://hentaijl.com/"
  ["uncensoredhentai"]="https://uncensoredhentai.xxx/"  
  ["JKanimes"]="https://jkanime.net/"
  ["hentaiJK"]="https://hentaijk.com/"
  ["Bancolombia"]="https://svpersonas.apps.bancolombia.com/autenticacion"
  ["Search Pirate"]="https://search.brave.com/"
  ["Google"]="https://www.google.com/"
  ["Perplexity"]="https://www.perplexity.ai/"
  ["Gmail"]="https://mail.google.com"
  ["Google Photos"]="http://photos.google.com/"
  ["Correo UdeA"]="https://mail.google.com/mail/u/0/#inbox"
  ["Ude@"]="https://udearroba.udea.edu.co/internos/login/index.php"
  ["Ingeni@"]="https://virtualingenieriaudea.co/"
  ["UdeA Drive"]="https://drive.google.com/drive/my-drive"
  ["Drive"]="https://drive.google.com/drive/my-drive"
  ["Scrips backup"]="https://drive.google.com/drive/folders/1ZQNW6ZgKXnub-Us-pOPACplnM5SbDhPB"
  ["Entrega Podcst ingles"]="https://drive.google.com/drive/folders/1wi8Oqb3U8LpAK0N6dOxB-Dgk7kkpoTJ3?usp=sharing"
  ["Calendar"]="https://calendar.google.com/calendar/u/0/r"
  ["Meet.google"]="https://meet.google.com/landing"
  ["Monkeytype"]="https://monkeytype.com/"
  ["Google Maps"]="https://maps.google.com/"
  ["cinecalidad.mx"]="https://cine-calidad.mx/"
  ["Registo clases Universidad"]="https://docs.google.com/spreadsheets/d/1FC7W_-hErSNBsY0piSoW-PuWROAZ5RvRkxc0qjY10fc/edit?usp=sharing"
  ["History of Engineering"]="https://docs.google.com/document/d/1w2sU__RWZxfhUSgmX_0MkIvpuQ_umPmc1IF8DyURcHo/edit?tab=t.0"
  ["Love Next Door 1"]="https://www.doramasyt.com/dorama/amor-en-la-puerta-de-al-lado-latino-sub-espanol"
  ["Love Next Door 2"]="https://doramasflix.in/doramas-online/love-next-door"
  ["It's ok not to be ok"]="https://www.doramasyt.com/dorama/its-okay-to-not-be-okay-sub-espanol"
  ["King the land"]="https://www.doramasyt.com/dorama/king-the-land-latino-sub-espanol"
  ["La reina de las lagrimas"]="https://www.doramasyt.com/dorama/la-reina-de-las-lagrimas-latino-sub-espanol"
  ["Twenty-Five, Twenty-One"]="https://www.doramasyt.com/dorama/twenty-five-twenty-one-sub-espanol"
  ["Amor entre lineas"]="https://www.doramasyt.com/dorama/amor-entre-lineas-latino-sub-espanol"
  ["Un novio por suscripcion"]="https://www.doramasyt.com/dorama/un-novio-por-suscripcion-latino-sub-espanol"
  ["Bon appetit mangestad"]="https://www.doramasyt.com/dorama/bon-appetit-majestad-latino-sub-espanol"
  ["Queen of Divorce"]="https://www.doramasyt.com/dorama/queen-of-divorce-sub-espanol"
  ["Nos vemos en la oficina"]="https://www.doramasyt.com/dorama/nos-vemos-en-la-oficina-latino-sub-espanol"
  ["Cashman"]="https://tioplus.app/serie/cashman"
  ["Amor en el laboratorio"]="https://www.doramasyt.com/dorama/amor-en-el-laboratorio-latino-sub-espanol"
  ["Tastefully Yours/el sabor de lo nuesto"]="https://doramasflix.in/doramas-online/tastefully-yours"
  ["Acaramelados/our stiky love fav"]="https://doramasflix.in/doramas-online/our-sticky-love"
  ["Steven Universe"]="https://myflixerz.day/episodes/steven-universe-season-1-episode-1/"
  ["El genio y los deseos"]="https://www.doramasyt.com/dorama/el-genio-y-los-deseos-genie-make-a-wish-latino-sub-espanol"
  ["La reina de la confianza"]="https://tioplus.app/serie/la-reina-de-la-confianza"
  ["Lovely runner"]="https://www.doramasyt.com/dorama/corredora-encantadora-latino-sub-espanol"
  ["Ski into love"]="https://www.doramasyt.com/dorama/ski-into-love-sub-espanol"
  ["Love Reset fav"]="https://www.doramasyt.com/dorama/love-reset-sub-espanol"
  ["XVideos"]="https://www.xvideos.com/"
  ["Pornhub"]="https://es.pornhub.com/"
  ["My with superman S3"]="https://myflixerz.day/series/my-adventures-with-superman-eurbg/"
  ["Google Docs"]="https://docs.new"
  ["Google slides"]="https://slides.new"
  ["Love scenery"]="https://www.doramasyt.com/dorama/love-scenery-sub-espanol"
  ["Los 4 fantasticos 2025"]="https://lamovie.org/peliculas/los-4-fantasticos-primeros-pasos-2025/"
  ["My mini mart"]="https://www.youtube.com/playables/Ugkxto-OwJZo4rm8Xl2Nj3K403nHlYThf-sr"
  ["Aquarium Land"]="https://www.youtube.com/playables/UgkxwgDLkWx1arqo3OTf3msG3XHtU9JTIf1k"
  ["Decor life"]="https://www.youtube.com/playables/UgkxW0zdrtok4czk5IE1sj4MTiaFk45aHfwF"
  ["Simulacion de evolucion"]="https://www.youtube.com/playables/UgkxxJFnJx0jogPkEtc1bICU4EL2rbUW8kE5"
  ["Mi adorable demonio"]="https://www.doramasyt.com/dorama/mi-adorable-demonio-latino-sub-espanol"
  ["Amor de mentira Fav"]="https://www.doramasyt.com/dorama/amor-de-mentira-latino-sub-espanol"
  ["Monthly Magazine Home Fav"]="https://www.doramasyt.com/dorama/monthly-magazine-home-sub-espanol"
  ["La Sonrisa Se Ha Ido De Tus Ojos Fav"]="https://www.doramasyt.com/dorama/la-sonrisa-se-ha-ido-de-tus-ojos-latino-sub-espanol"
  ["Love Reset Fav"]="https://www.doramasyt.com/dorama/love-reset-sub-espanol"
  ["Teach you a lesson"]="https://doramasflix.in/doramas-online/teach-you-a-lesson"
  ["Beso dinamita"]="https://www.doramasyt.com/dorama/beso-dinamita-latino-sub-espanol"
  ["Belleza verdadera"]="https://www.doramasyt.com/dorama/true-beauty-sub-espanol"
  ["El amor es como un chachacha"]="https://www.doramasyt.com/dorama/el-amor-es-como-el-chachacha-sub-espanol"
  ["Whats wrong with sercretary kim"]="https://www.doramasyt.com/dorama/whats-wrong-with-secretary-kim-sub-espanol"
  ["Mi nemesis con aires de grandeza"]="https://www.doramasyt.com/dorama/mi-nemesis-con-aires-de-realeza-latino-sub-espanol"
  ["Propuesta laboral fav romance"]="https://www.doramasyt.com/dorama/propuesta-laboral-a-business-proposal-latino-sub-espanol"
  ["House of the dragon"]="https://lamovie.org/series/house-of-the-dragon-2022/"
  ["Word"]="https://word.cloud.microsoft/"
  ["El mentalista"]="https://tioplus.app/serie/el-mentalista"
  ["Power Point"]="https://powerpoint.cloud.microsoft/"
  ["Base Datos Profesoes Materias"]="https://ayudame2.udea.edu.co/php_mares/do.php?app=pub_cuposprog"
  ["Oferta academica"]="https://matricula.udea.edu.co/index.php"
  ["Matricula"]="https://matricula.udea.edu.co/index.php"
  ["Zoom - Algebra lineal"]="https://udearroba.zoom.us/j/94451769492?uname=JUAN%20ESTEBAN%20VELEZ%20HINCAPIE#success"
  ["Zoom - Calculo integral"]="https://udearroba.zoom.us/j/95441635988?uname=JUAN%20ESTEBAN%20VELEZ%20HINCAPIE#success"
  ["Zoom - Fisica Mecanica"]="https://udearroba.zoom.us/j/99982358988?uname=JUAN%20ESTEBAN%20VELEZ%20HINCAPIE#success"
  ["Zoom - Ingles V"]="https://udea.zoom.us/j/97057341996#success"
)

selection=$(printf "%s\n" "${!sites[@]}" | sort | fuzzel --dmenu --prompt="Sitios: ")

if [ -n "$selection" ]; then
    case "$selection" in
        "Correo UdeA"|"Ude@"|"Matricula"|"UdeA Drive"|"Ingeni@"|"Zoom - Algebra lineal"|"Zoom - Calculo integral"|"Zoom - Fisica Mecanica"|"Zoom - Ingles V")
            google-chrome-stable "${sites[$selection]}" &
            ;;
        "XVideos"|"Pornhub")
            brave-browser --tor "${sites[$selection]}" &
            ;;
        *)
            xdg-open "${sites[$selection]}" &
            ;;
    esac
fi
